// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/admin/config.proto

package admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config is the settings for Commander.
type Config struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	ContextPath          string   `protobuf:"bytes,2,opt,name=contextPath,proto3" json:"contextPath,omitempty"`
	PublicPath           string   `protobuf:"bytes,3,opt,name=publicPath,proto3" json:"publicPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3758320803bf4c04, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Config) GetContextPath() string {
	if m != nil {
		return m.ContextPath
	}
	return ""
}

func (m *Config) GetPublicPath() string {
	if m != nil {
		return m.PublicPath
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "v2ray.core.app.admin.Config")
}

func init() { proto.RegisterFile("app/admin/config.proto", fileDescriptor_3758320803bf4c04) }

var fileDescriptor_3758320803bf4c04 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2c, 0x28, 0xd0,
	0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0xd3, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x29, 0x33, 0x2a, 0x4a, 0xac, 0xd4, 0x4b, 0xce, 0x2f, 0x4a, 0xd5, 0x4b,
	0x2c, 0x28, 0xd0, 0x03, 0x2b, 0x51, 0x8a, 0xe3, 0x62, 0x73, 0x06, 0xab, 0x12, 0x12, 0xe2, 0x62,
	0x49, 0x4c, 0x49, 0x29, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x14, 0xb8,
	0xb8, 0x93, 0xf3, 0xf3, 0x4a, 0x52, 0x2b, 0x4a, 0x02, 0x12, 0x4b, 0x32, 0x24, 0x98, 0xc0, 0x52,
	0xc8, 0x42, 0x42, 0x72, 0x5c, 0x5c, 0x05, 0xa5, 0x49, 0x39, 0x99, 0xc9, 0x60, 0x05, 0xcc, 0x60,
	0x05, 0x48, 0x22, 0x4e, 0x56, 0x5c, 0x12, 0xc9, 0xf9, 0xb9, 0x7a, 0xd8, 0xec, 0x0e, 0x60, 0x8c,
	0x62, 0x05, 0x33, 0x56, 0x31, 0x89, 0x84, 0x19, 0x05, 0x25, 0x56, 0xea, 0x39, 0x83, 0xe4, 0x1d,
	0x0b, 0x0a, 0xf4, 0x1c, 0x41, 0xc2, 0x49, 0x6c, 0x60, 0x87, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xcb, 0x54, 0x8b, 0xac, 0xd2, 0x00, 0x00, 0x00,
}
